feat: add mobile menu for course chapters
yaralahruthik/frontend-hire-v2-legacy pull request #8
Opened 2024-10-09 17:44 UTC by nitan-jana

closes #7

2024-10-09 17:56 UTC, yaralahruthik requested changes
Hmm, though this works. I feel like we should tap into ShadCN's component. It better aligns with the theme of the website.

2024-10-09 17:57 UTC, yaralahruthik commented
@NitanJana we should also use the icons from Radix

https://www.radix-ui.com/icons

2024-10-09 17:59 UTC, nitan-jana commented
Sure, will do that. I started with shadcn but then thought of implementing without it.

2024-10-09 18:02 UTC, yaralahruthik commented
> Sure, will do that. I started with shadcn but then thought of implementing without it.

This also allows you to understand how Astro and React integrate.

2024-10-10 06:17 UTC, yaralahruthik commented on src/components/Sidebar.tsx
Need to make this lowercase. The convention for this project is to have all files in lowercase or kebab-case.

2024-10-10 06:19 UTC, yaralahruthik commented on src/components/Sidebar.tsx
> +				</SheetHeader>
Do we need this?

2024-10-10 06:21 UTC, yaralahruthik commented on src/components/Sidebar.tsx
In fact, I am a little confused reading this component. 

Is it a generic component? Cause I see things specific to Menu etc.,

Instead, we can make a dedicated component called MobileCourseMenu (mobile-course-menu.tsx) and use that. We can also add another slot for the same.

2024-10-10 06:22 UTC, yaralahruthik commented on src/components/Sidebar.tsx
> +export default function Sidebar({ children }: SidebarProps) {
React.PropsWithChildren can be used here instead of SideBarProps

2024-10-10 06:23 UTC, yaralahruthik requested changes
Some changes and clarifications needed

2024-10-10 06:24 UTC, nitan-jana commented on src/components/Sidebar.tsx
> +				</SheetHeader>
Radix suggests adding these for accessibility purposes, if removed throws error and warnings.

2024-10-10 06:26 UTC, nitan-jana commented on src/components/Sidebar.tsx
alright.

2024-10-10 06:37 UTC, nitan-jana commented on src/components/Sidebar.tsx
> Instead, we can make a dedicated component called MobileCourseMenu (mobile-course-menu.tsx) and use that. We can also add another slot for the same.

You're right, that makes more sense.

2024-10-10 07:21 UTC, yaralahruthik commented on src/components/Sidebar.tsx
> +				</SheetHeader>
Yes, create a more specific component as suggested above so that we can add the title and description.

2024-10-10 07:46 UTC, yaralahruthik commented on src/components/mobile-course-menu.tsx
> +	chapters: { title: string; slug: string }[];
Would be a good idea to get this type from the collections?

Check the `chapter-list.astro` file

2024-10-10 07:46 UTC, yaralahruthik commented on src/components/mobile-course-menu.tsx
> +type Props = {
Name this `MobileCourseMenuProps`, just a convention many like to use.

2024-10-10 07:48 UTC, yaralahruthik commented on src/components/mobile-course-menu.tsx
> +	chapters: { title: string; slug: string }[];
Aah. Wait, I see this typed the same even in that file.

Can we do a single source of truth for this?

2024-10-10 07:50 UTC, yaralahruthik approved these changes
Nevermind, I'll do some refactoring!

2024-10-10 07:51 UTC, merged

2024-10-10 07:54 UTC, nitan-jana commented on src/components/mobile-course-menu.tsx
> +	chapters: { title: string; slug: string }[];
Yes, we can get them from `content/config.ts`